language: ruby
sudo: required
rvm:
- 2.2.4
script:
  - RAILS_ENV=test bundle exec rake db:migrate:reset --trace
  - RAILS_ENV=test bundle exec rake db:seed
notifications:
  email:
    - a1517ko@aiit.ac.jp
    - a15z2hk@aiit.ac.jp
    - a1548sy@aiit.ac.jp
    - a1534yt@aiit.ac.jp
    - a1419ys@aiit.ac.jp
