language: ruby
sudo: required
rvm:
- 2.2.4
script:
  - RAILS_ENV=test bundle exec rake db:migrate:reset --trace
  - RAILS_ENV=test bundle exec rake db:seed
deploy:
  provider: heroku
  api_key:
    secure: PAV/wVTAceO/2WaFaBuvqhajM1wBukPxG9yn0OYGA1D66Lx0R7lKYkNnwX4BHEIqn0W04xiW6zTXMq3VqZ9AwFFmy9nNKC1HW4BFnvGwAv9k3qm7FvCnPYY1LPqd+vOlhYWxSjsjalgA4roliKF7gdGtALRlsO1PiJa338A0vOO1cBPaHdecq4VQcCJ3NX30ALj3U2k2Jl8ZSWMrBXAi7WVLe65fGgZgFrSrAnrhPSTpBzQd9w7bT97kIFvbbiupMl+yrCH/+Xs300vKWKr9fPPo8LbytLB3j+5n1N0VPQm5AsVMGr5mtN+Kqalh/aV8XviFBEkKvvjPURsSDVmjbO2dgJX4HfQp1vOLYxi9LpUBrFH9SQ5Mbj7AVoX6LlcstXRi7xk+tYohHQuMKokiCFHmUCLJMuq1yDzbBMs9KQ5Rlr9Gm/TYfOqM0Oi2uCdhV6EreJxu56R9bH4UZtvKg5DfWaahlPMcu0b8MK068UWpOv2ky3HUCXqi94vjbt+eS+tHGl29FZNJ62einTd870uXedI53ecrNwSHapxyAPHSCZ4Gcyzo2yN/8MItj7Q+goDivdKhYQyjJTMaGtQhRYMwIB2xPZ7jms7CZ7v9pFgioF+Z66CM7A1ULQTTTRC5mshrfiGe3JaWefR3XMSyxmZukuliPAzHLS5M5c58Suk=
  app: tabitomo
  on:
    repo: 2016chubachi/tabitomo
notifications:
  email:
    - a1517ko@aiit.ac.jp
    - a15z2hk@aiit.ac.jp
    - a1548sy@aiit.ac.jp
    - a1534yt@aiit.ac.jp
    - a1419ys@aiit.ac.jp
    
# travis ci セット手順
# gem install travis --インストールしていない場合
# travis login
# heroku login
# travis init   --.travis.ymlファイルを作成する
# travis setup heroku

# heroku 本番環境postgreSQLリセットリセットコマンド
# heroku pg:reset DATABASE --app tabitomo --confirm tabitomo
# heroku run rake db:migrate --app tabitomo
# heroku run rake db:seed --app tabitomo