#国　countries
# Country.create(code: "AD", text_ja: "アンドラ", text_en: "Andorra", text_ko: "안도라", text_zh: " 安道尔")
# Country.create(code: "AE", text_ja: "アラブ首長国連邦", text_en: "United Arab Emirates", text_ko: "아랍에미리트", text_zh: " 阿联酋")
# Country.create(code: "AF", text_ja: "アフガニスタン", text_en: "Afghanistan", text_ko: "아프가니스탄", text_zh: " 阿富汗")
# Country.create(code: "AG", text_ja: "アンティグア・バーブーダ", text_en: "Antigua and Barbuda", text_ko: "바부다", text_zh: " 安地卡及巴布達")
# Country.create(code: "AI", text_ja: "アンギラ", text_en: "Anguilla", text_ko: "앵귈라", text_zh: " 安圭拉")
# Country.create(code: "AL", text_ja: "アルバニア", text_en: "Albania", text_ko: "알바니아", text_zh: " 阿尔巴尼亚")
# Country.create(code: "AM", text_ja: "アルメニア", text_en: "Armenia", text_ko: "아르메니아", text_zh: " 亞美尼亞")
# Country.create(code: "AO", text_ja: "アンゴラ", text_en: "Angola", text_ko: "앙골라", text_zh: " 安哥拉")
# Country.create(code: "AQ", text_ja: "南極", text_en: "Antarctica", text_ko: "남극", text_zh: " 南极洲")
# Country.create(code: "AR", text_ja: "アルゼンチン", text_en: "Argentina", text_ko: "아르헨티나", text_zh: " 阿根廷")
# Country.create(code: "AS", text_ja: "アメリカ領サモア", text_en: "American Samoa", text_ko: "아메리칸사모아", text_zh: " 美属萨摩亚")
# Country.create(code: "AT", text_ja: "オーストリア", text_en: "Austria", text_ko: "오스트리아", text_zh: " 奥地利")
Country.create(code: "AU", text_ja: "オーストラリア", text_en: "Australia", text_ko: "오스트레일리아", text_zh: " 澳大利亚",display_order: 1)
# Country.create(code: "AW", text_ja: "アルバ", text_en: "Aruba", text_ko: "아루바", text_zh: " 阿鲁巴")
# Country.create(code: "AX", text_ja: "オーランド諸島", text_en: "Åland Islands", text_ko: "제도", text_zh: " 奥兰")
# Country.create(code: "AZ", text_ja: "アゼルバイジャン", text_en: "Azerbaijan", text_ko: "아제르바이잔", text_zh: " 阿塞拜疆")
# Country.create(code: "BA", text_ja: "ボスニア・ヘルツェゴビナ", text_en: "Bosnia and Herzegovina", text_ko: "헤르체고비나", text_zh: " 波斯尼亚和黑塞哥维那")
# Country.create(code: "BB", text_ja: "バルバドス", text_en: "Barbados", text_ko: "바베이도스", text_zh: " 巴巴多斯")
# Country.create(code: "BD", text_ja: "バングラデシュ", text_en: "Bangladesh", text_ko: "방글라데시", text_zh: " 孟加拉国")
# Country.create(code: "BE", text_ja: "ベルギー", text_en: "Belgium", text_ko: "벨기에", text_zh: " 比利時")
# Country.create(code: "BF", text_ja: "ブルキナファソ", text_en: "Burkina Faso", text_ko: "부르키나파소", text_zh: " 布吉納法索")
# Country.create(code: "BG", text_ja: "ブルガリア", text_en: "Bulgaria", text_ko: "불가리아", text_zh: " 保加利亚")
Country.create(code: "BH", text_ja: "バーレーン", text_en: "Bahrain", text_ko: "바레인", text_zh: " 巴林" ,display_order: 2)
# Country.create(code: "BI", text_ja: "ブルンジ", text_en: "Burundi", text_ko: "부룬디", text_zh: " 布隆迪")
# Country.create(code: "BJ", text_ja: "ベナン", text_en: "Benin", text_ko: "베냉", text_zh: " 贝宁")
# Country.create(code: "BM", text_ja: "バミューダ", text_en: "Bermuda", text_ko: "버뮤다", text_zh: " 百慕大")
# Country.create(code: "BN", text_ja: "ブルネイ・ダルサラーム", text_en: "Brunei Darussalam", text_ko: "브루나이", text_zh: " 文莱")
# Country.create(code: "BO", text_ja: "ボリビア多民族国", text_en: "Bolivia, Plurinational State of", text_ko: "볼리비아", text_zh: " 玻利维亚")
Country.create(code: "BR", text_ja: "ブラジル", text_en: "Brazil", text_ko: "브라질", text_zh: " 巴西" ,display_order: 3)
# Country.create(code: "BS", text_ja: "バハマ", text_en: "Bahamas", text_ko: "바하마", text_zh: " 巴哈马")
# Country.create(code: "BT", text_ja: "ブータン", text_en: "Bhutan", text_ko: "부탄", text_zh: " 不丹")
# Country.create(code: "BV", text_ja: "ブーベ島", text_en: "Bouvet Island", text_ko: "섬", text_zh: " 布韦岛")
# Country.create(code: "BW", text_ja: "ボツワナ", text_en: "Botswana", text_ko: "보츠와나", text_zh: " 博茨瓦纳")
# Country.create(code: "BY", text_ja: "ベラルーシ", text_en: "Belarus", text_ko: "벨라루스", text_zh: " 白俄羅斯")
# Country.create(code: "BZ", text_ja: "ベリーズ", text_en: "Belize", text_ko: "벨리즈", text_zh: " 伯利兹")
Country.create(code: "CA", text_ja: "カナダ", text_en: "Canada", text_ko: "캐나다", text_zh: " 加拿大",display_order: 4)
# Country.create(code: "CC", text_ja: "ココス（キーリング）諸島", text_en: "Cocos (Keeling) Islands", text_ko: "제도", text_zh: " 科科斯（基林）群島")
# Country.create(code: "CD", text_ja: "コンゴ民主共和国", text_en: "Congo, the Democratic Republic of the", text_ko: "공화국", text_zh: " 刚果（金）")
# Country.create(code: "CF", text_ja: "中央アフリカ共和国", text_en: "Central African Republic", text_ko: "공화국", text_zh: " 中非")
# Country.create(code: "CG", text_ja: "コンゴ共和国", text_en: "Congo", text_ko: "공화국", text_zh: " 刚果（布）")
Country.create(code: "CH", text_ja: "スイス", text_en: "Switzerland", text_ko: "스위스", text_zh: " 瑞士",display_order: 5)
# Country.create(code: "CI", text_ja: "コートジボワール", text_en: "Côte d'Ivoire", text_ko: "코트디부아르", text_zh: " 科特迪瓦")
# Country.create(code: "CK", text_ja: "クック諸島", text_en: "Cook Islands", text_ko: "제도", text_zh: " 庫克群島")
# Country.create(code: "CL", text_ja: "チリ", text_en: "Chile", text_ko: "칠레", text_zh: " 智利")
# Country.create(code: "CM", text_ja: "カメルーン", text_en: "Cameroon", text_ko: "카메룬", text_zh: " 喀麦隆")
Country.create(code: "CN", text_ja: "中華人民共和国", text_en: "China", text_ko: "중화인민공화국", text_zh: " 中国",display_order: 6)
# Country.create(code: "CO", text_ja: "コロンビア", text_en: "Colombia", text_ko: "콜롬비아", text_zh: " 哥伦比亚")
# Country.create(code: "CR", text_ja: "コスタリカ", text_en: "Costa Rica", text_ko: "코스타리카", text_zh: " 哥斯达黎加")
# Country.create(code: "CU", text_ja: "キューバ", text_en: "Cuba", text_ko: "쿠바", text_zh: " 古巴")
# Country.create(code: "CV", text_ja: "カーボベルデ", text_en: "Cape Verde", text_ko: "카보베르데", text_zh: " 佛得角")
# Country.create(code: "CX", text_ja: "クリスマス島", text_en: "Christmas Island", text_ko: "섬", text_zh: " 圣诞岛")
# Country.create(code: "CY", text_ja: "キプロス", text_en: "Cyprus", text_ko: "키프로스", text_zh: " 賽普勒斯")
# Country.create(code: "CZ", text_ja: "チェコ", text_en: "Czech Republic", text_ko: "체코", text_zh: " 捷克")
Country.create(code: "DE", text_ja: "ドイツ", text_en: "Germany", text_ko: "독일", text_zh: " 德國",display_order: 7)
# Country.create(code: "DJ", text_ja: "ジブチ", text_en: "Djibouti", text_ko: "지부티", text_zh: " 吉布提")
Country.create(code: "DK", text_ja: "デンマーク", text_en: "Denmark", text_ko: "덴마크", text_zh: " 丹麥",display_order: 8)
# Country.create(code: "DM", text_ja: "ドミニカ国", text_en: "Dominica", text_ko: "연방", text_zh: " 多米尼克")
# Country.create(code: "DO", text_ja: "ドミニカ共和国", text_en: "Dominican Republic", text_ko: "공화국", text_zh: " 多米尼加")
# Country.create(code: "DZ", text_ja: "アルジェリア", text_en: "Algeria", text_ko: "알제리", text_zh: " 阿尔及利亚")
# Country.create(code: "EC", text_ja: "エクアドル", text_en: "Ecuador", text_ko: "에콰도르", text_zh: " 厄瓜多尔")
# Country.create(code: "EE", text_ja: "エストニア", text_en: "Estonia", text_ko: "에스토니아", text_zh: " 爱沙尼亚")
# Country.create(code: "EG", text_ja: "エジプト", text_en: "Egypt", text_ko: "이집트", text_zh: " 埃及")
# Country.create(code: "EH", text_ja: "西サハラ", text_en: "Western Sahara", text_ko: "서사하라", text_zh: " 阿拉伯撒哈拉民主共和国")
# Country.create(code: "ER", text_ja: "エリトリア", text_en: "Eritrea", text_ko: "에리트레아", text_zh: " 厄立特里亚")
Country.create(code: "ES", text_ja: "スペイン", text_en: "Spain", text_ko: "스페인", text_zh: " 西班牙",display_order: 9)
# Country.create(code: "ET", text_ja: "エチオピア", text_en: "Ethiopia", text_ko: "에티오피아", text_zh: " 衣索比亞")
Country.create(code: "FI", text_ja: "フィンランド", text_en: "Finland", text_ko: "핀란드", text_zh: " 芬兰",display_order: 10)
# Country.create(code: "FJ", text_ja: "フィジー", text_en: "Fiji", text_ko: "피지", text_zh: " 斐济")
# Country.create(code: "FK", text_ja: "フォークランド（マルビナス）諸島", text_en: "Falkland Islands (Malvinas)", text_ko: "제도", text_zh: " 福克蘭群島")
# Country.create(code: "FM", text_ja: "ミクロネシア連邦", text_en: "Micronesia, Federated States of", text_ko: "연방", text_zh: " 密克羅尼西亞聯邦")
# Country.create(code: "FO", text_ja: "フェロー諸島", text_en: "Faroe Islands", text_ko: "제도", text_zh: " 法罗群岛")
Country.create(code: "FR", text_ja: "フランス", text_en: "France", text_ko: "프랑스", text_zh: " 法国",display_order: 11)
# Country.create(code: "GA", text_ja: "ガボン", text_en: "Gabon", text_ko: "가봉", text_zh: " 加彭")
Country.create(code: "GB", text_ja: "イギリス", text_en: "United Kingdom", text_ko: "영국", text_zh: " 英國",display_order: 12)
# Country.create(code: "GD", text_ja: "グレナダ", text_en: "Grenada", text_ko: "그레나다", text_zh: " 格瑞那達")
# Country.create(code: "GE", text_ja: "ジョージア", text_en: "Georgia", text_ko: "조지아", text_zh: " 格鲁吉亚")
# Country.create(code: "GF", text_ja: "フランス領ギアナ", text_en: "French Guiana", text_ko: "기아나", text_zh: " 法属圭亚那")
# Country.create(code: "GG", text_ja: "ガーンジー", text_en: "Guernsey", text_ko: "섬", text_zh: " 根西")
# Country.create(code: "GH", text_ja: "ガーナ", text_en: "Ghana", text_ko: "가나", text_zh: " 加纳")
# Country.create(code: "GI", text_ja: "ジブラルタル", text_en: "Gibraltar", text_ko: "지브롤터", text_zh: " 直布罗陀")
# Country.create(code: "GL", text_ja: "グリーンランド", text_en: "Greenland", text_ko: "그린란드", text_zh: " 格陵兰")
# Country.create(code: "GM", text_ja: "ガンビア", text_en: "Gambia", text_ko: "감비아", text_zh: " 冈比亚")
# Country.create(code: "GN", text_ja: "ギニア", text_en: "Guinea", text_ko: "기니", text_zh: " 几内亚")
# Country.create(code: "GP", text_ja: "グアドループ", text_en: "Guadeloupe", text_ko: "과들루프", text_zh: " 瓜德罗普")
# Country.create(code: "GQ", text_ja: "赤道ギニア", text_en: "Equatorial Guinea", text_ko: "기니", text_zh: " 赤道几内亚")
# Country.create(code: "GR", text_ja: "ギリシャ", text_en: "Greece", text_ko: "그리스", text_zh: " 希臘")
# Country.create(code: "GS", text_ja: "サウスジョージア・サウスサンドウィッチ諸島", text_en: "South Georgia and the South Sandwich Islands", text_ko: "제도", text_zh: " 南乔治亚和南桑威奇群岛")
# Country.create(code: "GT", text_ja: "グアテマラ", text_en: "Guatemala", text_ko: "과테말라", text_zh: " 危地马拉")
# Country.create(code: "GU", text_ja: "グアム", text_en: "Guam", text_ko: "괌", text_zh: " 關島")
# Country.create(code: "GW", text_ja: "ギニアビサウ", text_en: "Guinea-Bissau", text_ko: "기니비사우", text_zh: " 几内亚比绍")
# Country.create(code: "GY", text_ja: "ガイアナ", text_en: "Guyana", text_ko: "가이아나", text_zh: " 圭亚那")
Country.create(code: "HK", text_ja: "香港", text_en: "Hong Kong", text_ko: "홍콩", text_zh: " 香港",display_order: 13)
# Country.create(code: "HM", text_ja: "ハード島とマクドナルド諸島", text_en: "Heard Island and McDonald Islands", text_ko: "제도", text_zh: " 赫德岛和麦克唐纳群岛")
# Country.create(code: "HN", text_ja: "ホンジュラス", text_en: "Honduras", text_ko: "온두라스", text_zh: " 宏都拉斯")
# Country.create(code: "HR", text_ja: "クロアチア", text_en: "Croatia", text_ko: "크로아티아", text_zh: " 克罗地亚")
# Country.create(code: "HT", text_ja: "ハイチ", text_en: "Haiti", text_ko: "아이티", text_zh: " 海地")
# Country.create(code: "HU", text_ja: "ハンガリー", text_en: "Hungary", text_ko: "헝가리", text_zh: " 匈牙利")
# Country.create(code: "ID", text_ja: "インドネシア", text_en: "Indonesia", text_ko: "인도네시아", text_zh: " 印尼")
# Country.create(code: "IE", text_ja: "アイルランド", text_en: "Ireland", text_ko: "아일랜드", text_zh: " 爱尔兰")
Country.create(code: "IL", text_ja: "イスラエル", text_en: "Israel", text_ko: "이스라엘", text_zh: " 以色列",display_order: 14)
# Country.create(code: "IM", text_ja: "マン島", text_en: "Isle of Man", text_ko: "섬", text_zh: " 马恩岛")
Country.create(code: "IN", text_ja: "インド", text_en: "India", text_ko: "인도", text_zh: " 印度",display_order: 15)
# Country.create(code: "IO", text_ja: "イギリス領インド洋地域", text_en: "British Indian Ocean Territory", text_ko: "지역", text_zh: " 英屬印度洋領地")
# Country.create(code: "IQ", text_ja: "イラク", text_en: "Iraq", text_ko: "이라크", text_zh: " 伊拉克")
# Country.create(code: "IR", text_ja: "イラン・イスラム共和国", text_en: "Iran, Islamic Republic of", text_ko: "이란", text_zh: " 伊朗")
# Country.create(code: "IS", text_ja: "アイスランド", text_en: "Iceland", text_ko: "아이슬란드", text_zh: " 冰島")
Country.create(code: "IT", text_ja: "イタリア", text_en: "Italy", text_ko: "이탈리아", text_zh: " 義大利",display_order: 16)
# Country.create(code: "JE", text_ja: "ジャージー", text_en: "Jersey", text_ko: "섬", text_zh: " 澤西")
# Country.create(code: "JM", text_ja: "ジャマイカ", text_en: "Jamaica", text_ko: "자메이카", text_zh: " 牙买加")
# Country.create(code: "JO", text_ja: "ヨルダン", text_en: "Jordan", text_ko: "요르단", text_zh: " 约旦")
Country.create(code: "JP", text_ja: "日本", text_en: "Japan", text_ko: "일본", text_zh: " 日本",display_order: 17)
# Country.create(code: "KE", text_ja: "ケニア", text_en: "Kenya", text_ko: "케냐", text_zh: " 肯尼亚")
# Country.create(code: "KG", text_ja: "キルギス", text_en: "Kyrgyzstan", text_ko: "키르기스스탄", text_zh: " 吉尔吉斯斯坦")
# Country.create(code: "KH", text_ja: "カンボジア", text_en: "Cambodia", text_ko: "캄보디아", text_zh: " 柬埔寨")
# Country.create(code: "KI", text_ja: "キリバス", text_en: "Kiribati", text_ko: "키리바시", text_zh: " 基里巴斯")
# Country.create(code: "KM", text_ja: "コモロ", text_en: "Comoros", text_ko: "코모로", text_zh: " 科摩罗")
# Country.create(code: "KN", text_ja: "セントクリストファー・ネイビス", text_en: "Saint Kitts and Nevis", text_ko: "네비스", text_zh: " 圣基茨和尼维斯")
# Country.create(code: "KP", text_ja: "朝鮮民主主義人民共和国", text_en: "Korea, Democratic People's Republic of", text_ko: "조선민주주의인민공화국", text_zh: " 朝鲜")
Country.create(code: "KR", text_ja: "大韓民国", text_en: "Korea, Republic of", text_ko: "대한민국", text_zh: " 韩国",display_order: 18)
# Country.create(code: "KW", text_ja: "クウェート", text_en: "Kuwait", text_ko: "쿠웨이트", text_zh: " 科威特")
# Country.create(code: "KY", text_ja: "ケイマン諸島", text_en: "Cayman Islands", text_ko: "제도", text_zh: " 开曼群岛")
# Country.create(code: "KZ", text_ja: "カザフスタン", text_en: "Kazakhstan", text_ko: "카자흐스탄", text_zh: " 哈萨克斯坦")
# Country.create(code: "LA", text_ja: "ラオス人民民主共和国", text_en: "Lao People's Democratic Republic", text_ko: "라오스", text_zh: " 老挝")
# Country.create(code: "LB", text_ja: "レバノン", text_en: "Lebanon", text_ko: "레바논", text_zh: " 黎巴嫩")
# Country.create(code: "LC", text_ja: "セントルシア", text_en: "Saint Lucia", text_ko: "세인트루시아", text_zh: " 圣卢西亚")
# Country.create(code: "LI", text_ja: "リヒテンシュタイン", text_en: "Liechtenstein", text_ko: "리히텐슈타인", text_zh: " 列支敦斯登")
# Country.create(code: "LK", text_ja: "スリランカ", text_en: "Sri Lanka", text_ko: "스리랑카", text_zh: " 斯里蘭卡")
# Country.create(code: "LR", text_ja: "リベリア", text_en: "Liberia", text_ko: "라이베리아", text_zh: " 利比里亚")
# Country.create(code: "LS", text_ja: "レソト", text_en: "Lesotho", text_ko: "레소토", text_zh: " 賴索托")
# Country.create(code: "LT", text_ja: "リトアニア", text_en: "Lithuania", text_ko: "리투아니아", text_zh: " 立陶宛")
# Country.create(code: "LU", text_ja: "ルクセンブルク", text_en: "Luxembourg", text_ko: "룩셈부르크", text_zh: " 卢森堡")
# Country.create(code: "LV", text_ja: "ラトビア", text_en: "Latvia", text_ko: "라트비아", text_zh: " 拉脫維亞")
# Country.create(code: "LY", text_ja: "リビア", text_en: "Libya", text_ko: "리비아", text_zh: " 利比亞")
# Country.create(code: "MA", text_ja: "モロッコ", text_en: "Morocco", text_ko: "모로코", text_zh: " 摩洛哥")
# Country.create(code: "MC", text_ja: "モナコ", text_en: "Monaco", text_ko: "모나코", text_zh: " 摩納哥")
# Country.create(code: "MD", text_ja: "モルドバ共和国", text_en: "Moldova, Republic of", text_ko: "몰도바", text_zh: " 摩尔多瓦")
# Country.create(code: "ME", text_ja: "モンテネグロ", text_en: "Montenegro", text_ko: "몬테네그로", text_zh: " 蒙特內哥羅")
# Country.create(code: "MG", text_ja: "マダガスカル", text_en: "Madagascar", text_ko: "마다가스카르", text_zh: " 马达加斯加")
# Country.create(code: "MH", text_ja: "マーシャル諸島", text_en: "Marshall Islands", text_ko: "제도", text_zh: " 马绍尔群岛")
# Country.create(code: "MK", text_ja: "マケドニア旧ユーゴスラビア共和国", text_en: "Macedonia, the former Yugoslav Republic of", text_ko: "공화국", text_zh: " 馬其頓")
# Country.create(code: "ML", text_ja: "マリ", text_en: "Mali", text_ko: "말리", text_zh: " 马里")
# Country.create(code: "MM", text_ja: "ミャンマー", text_en: "Myanmar", text_ko: "미얀마", text_zh: " 緬甸")
# Country.create(code: "MN", text_ja: "モンゴル", text_en: "Mongolia", text_ko: "몽골", text_zh: " 蒙古")
# Country.create(code: "MO", text_ja: "マカオ", text_en: "Macau", text_ko: "마카오", text_zh: " 澳門")
# Country.create(code: "MP", text_ja: "北マリアナ諸島", text_en: "Northern Mariana Islands", text_ko: "제도", text_zh: " 北馬里亞納群島")
# Country.create(code: "MQ", text_ja: "マルティニーク", text_en: "Martinique", text_ko: "마르티니크", text_zh: " 马提尼克")
# Country.create(code: "MR", text_ja: "モーリタニア", text_en: "Mauritania", text_ko: "모리타니", text_zh: " 毛里塔尼亚")
# Country.create(code: "MS", text_ja: "モントセラト", text_en: "Montserrat", text_ko: "몬트세랫", text_zh: " 蒙特塞拉特")
# Country.create(code: "MT", text_ja: "マルタ", text_en: "Malta", text_ko: "몰타", text_zh: " 馬爾他")
# Country.create(code: "MU", text_ja: "モーリシャス", text_en: "Mauritius", text_ko: "모리셔스", text_zh: " 模里西斯")
# Country.create(code: "MV", text_ja: "モルディブ", text_en: "Maldives", text_ko: "몰디브", text_zh: " 馬爾地夫")
# Country.create(code: "MW", text_ja: "マラウイ", text_en: "Malawi", text_ko: "말라위", text_zh: " 马拉维")
# Country.create(code: "MX", text_ja: "メキシコ", text_en: "Mexico", text_ko: "멕시코", text_zh: " 墨西哥")
Country.create(code: "MY", text_ja: "マレーシア", text_en: "Malaysia", text_ko: "말레이시아", text_zh: " 马来西亚",display_order: 19)
# Country.create(code: "MZ", text_ja: "モザンビーク", text_en: "Mozambique", text_ko: "모잠비크", text_zh: " 莫桑比克")
# Country.create(code: "NA", text_ja: "ナミビア", text_en: "Namibia", text_ko: "나미비아", text_zh: " 纳米比亚")
# Country.create(code: "NC", text_ja: "ニューカレドニア", text_en: "New Caledonia", text_ko: "누벨칼레도니", text_zh: " 新喀里多尼亞")
# Country.create(code: "NE", text_ja: "ニジェール", text_en: "Niger", text_ko: "니제르", text_zh: " 尼日尔")
# Country.create(code: "NF", text_ja: "ノーフォーク島", text_en: "Norfolk Island", text_ko: "섬", text_zh: " 诺福克岛")
# Country.create(code: "NG", text_ja: "ナイジェリア", text_en: "Nigeria", text_ko: "나이지리아", text_zh: " 奈及利亞")
# Country.create(code: "NI", text_ja: "ニカラグア", text_en: "Nicaragua", text_ko: "니카라과", text_zh: " 尼加拉瓜")
Country.create(code: "NL", text_ja: "オランダ", text_en: "Netherlands", text_ko: "네덜란드", text_zh: " 荷蘭",display_order: 20)
Country.create(code: "NO", text_ja: "ノルウェー", text_en: "Norway", text_ko: "노르웨이", text_zh: " 挪威",display_order: 21)
# Country.create(code: "NP", text_ja: "ネパール", text_en: "Nepal", text_ko: "네팔", text_zh: " 尼泊尔")
# Country.create(code: "NR", text_ja: "ナウル", text_en: "Nauru", text_ko: "나우루", text_zh: " 瑙鲁")
# Country.create(code: "NU", text_ja: "ニウエ", text_en: "Niue", text_ko: "니우에", text_zh: " 纽埃")
Country.create(code: "NZ", text_ja: "ニュージーランド", text_en: "New Zealand", text_ko: "뉴질랜드", text_zh: " 新西蘭",display_order: 22)
# Country.create(code: "OM", text_ja: "オマーン", text_en: "Oman", text_ko: "오만", text_zh: " 阿曼")
# Country.create(code: "PA", text_ja: "パナマ", text_en: "Panama", text_ko: "파나마", text_zh: " 巴拿马")
# Country.create(code: "PE", text_ja: "ペルー", text_en: "Peru", text_ko: "페루", text_zh: " 秘魯")
# Country.create(code: "PF", text_ja: "フランス領ポリネシア", text_en: "French Polynesia", text_ko: "폴리네시아", text_zh: " 法屬玻里尼西亞")
# Country.create(code: "PG", text_ja: "パプアニューギニア", text_en: "Papua New Guinea", text_ko: "파푸아뉴기니", text_zh: " 巴布亚新几内亚")
Country.create(code: "PH", text_ja: "フィリピン", text_en: "Philippines", text_ko: "필리핀", text_zh: " 菲律賓",display_order: 23)
# Country.create(code: "PK", text_ja: "パキスタン", text_en: "Pakistan", text_ko: "파키스탄", text_zh: " 巴基斯坦")
# Country.create(code: "PL", text_ja: "ポーランド", text_en: "Poland", text_ko: "폴란드", text_zh: " 波蘭")
# Country.create(code: "PM", text_ja: "サンピエール島・ミクロン島", text_en: "Saint Pierre and Miquelon", text_ko: "미클롱", text_zh: " 圣皮埃尔和密克隆")
# Country.create(code: "PN", text_ja: "ピトケアン", text_en: "Pitcairn", text_ko: "제도", text_zh: " 皮特凯恩群岛")
# Country.create(code: "PR", text_ja: "プエルトリコ", text_en: "Puerto Rico", text_ko: "푸에르토리코", text_zh: " 波多黎各")
# Country.create(code: "PS", text_ja: "パレスチナ", text_en: "Palestinian Territory, Occupied", text_ko: "팔레스타인", text_zh: " 巴勒斯坦")
Country.create(code: "PT", text_ja: "ポルトガル", text_en: "Portugal", text_ko: "포르투갈", text_zh: " 葡萄牙",display_order: 24)
# Country.create(code: "PW", text_ja: "パラオ", text_en: "Palau", text_ko: "팔라우", text_zh: " 帛琉")
# Country.create(code: "PY", text_ja: "パラグアイ", text_en: "Paraguay", text_ko: "파라과이", text_zh: " 巴拉圭")
# Country.create(code: "QA", text_ja: "カタール", text_en: "Qatar", text_ko: "카타르", text_zh: " 卡塔尔")
# Country.create(code: "RE", text_ja: "レユニオン", text_en: "Réunion", text_ko: "레위니옹", text_zh: " 留尼汪")
# Country.create(code: "RO", text_ja: "ルーマニア", text_en: "Romania", text_ko: "루마니아", text_zh: " 羅馬尼亞")
# Country.create(code: "RS", text_ja: "セルビア", text_en: "Serbia", text_ko: "세르비아", text_zh: " 塞爾維亞")
Country.create(code: "RU", text_ja: "ロシア連邦", text_en: "Russian Federation", text_ko: "러시아", text_zh: " 俄羅斯",display_order: 25)
# Country.create(code: "RW", text_ja: "ルワンダ", text_en: "Rwanda", text_ko: "르완다", text_zh: " 卢旺达")
Country.create(code: "SA", text_ja: "サウジアラビア", text_en: "Saudi Arabia", text_ko: "사우디아라비아", text_zh: " 沙烏地阿拉伯",display_order: 26)
# Country.create(code: "SB", text_ja: "ソロモン諸島", text_en: "Solomon Islands", text_ko: "제도", text_zh: " 所罗门群岛")
# Country.create(code: "SC", text_ja: "セーシェル", text_en: "Seychelles", text_ko: "세이셸", text_zh: " 塞舌尔")
# Country.create(code: "SD", text_ja: "スーダン", text_en: "Sudan", text_ko: "수단", text_zh: " 苏丹")
Country.create(code: "SE", text_ja: "スウェーデン", text_en: "Sweden", text_ko: "스웨덴", text_zh: " 瑞典",display_order: 27)
# Country.create(code: "SH", text_ja: "セントヘレナ・アセンションおよびトリスタンダクーニャ", text_en: "Saint Helena, Ascension and Tristan da Cunha", text_ko: "세인트헬레나", text_zh: " 聖赫勒拿")
# Country.create(code: "SI", text_ja: "スロベニア", text_en: "Slovenia", text_ko: "슬로베니아", text_zh: " 斯洛維尼亞")
# Country.create(code: "SJ", text_ja: "スヴァールバル諸島およびヤンマイエン島", text_en: "Svalbard and Jan Mayen", text_ko: "얀마옌", text_zh: "挪威 斯瓦尔巴群岛和扬马延岛")
# Country.create(code: "SK", text_ja: "スロバキア", text_en: "Slovakia", text_ko: "슬로바키아", text_zh: " 斯洛伐克")
# Country.create(code: "SL", text_ja: "シエラレオネ", text_en: "Sierra Leone", text_ko: "시에라리온", text_zh: " 塞拉利昂")
# Country.create(code: "SM", text_ja: "サンマリノ", text_en: "San Marino", text_ko: "산마리노", text_zh: " 圣马力诺")
# Country.create(code: "SN", text_ja: "セネガル", text_en: "Senegal", text_ko: "세네갈", text_zh: " 塞内加尔")
# Country.create(code: "SO", text_ja: "ソマリア", text_en: "Somalia", text_ko: "소말리아", text_zh: " 索馬利亞")
# Country.create(code: "SR", text_ja: "スリナム", text_en: "Suriname", text_ko: "수리남", text_zh: " 苏里南")
# Country.create(code: "SS", text_ja: "南スーダン", text_en: "South Sudan", text_ko: "남수단", text_zh: " 南蘇丹")
# Country.create(code: "ST", text_ja: "サントメ・プリンシペ", text_en: "Sao Tome and Principe", text_ko: "프린시페", text_zh: " 聖多美和普林西比")
# Country.create(code: "SV", text_ja: "エルサルバドル", text_en: "El Salvador", text_ko: "엘살바도르", text_zh: " 薩爾瓦多")
# Country.create(code: "SX", text_ja: "シント・マールテン（オランダ領）", text_en: "Sint Maarten (Dutch part)", text_ko: "신트마르턴", text_zh: " 荷屬聖馬丁")
# Country.create(code: "SY", text_ja: "シリア・アラブ共和国", text_en: "Syrian Arab Republic", text_ko: "시리아", text_zh: " 叙利亚")
# Country.create(code: "SZ", text_ja: "スワジランド", text_en: "Swaziland", text_ko: "스와질란드", text_zh: " 斯威士兰")
# Country.create(code: "TC", text_ja: "タークス・カイコス諸島", text_en: "Turks and Caicos Islands", text_ko: "제도", text_zh: " 特克斯和凯科斯群岛")
# Country.create(code: "TD", text_ja: "チャド", text_en: "Chad", text_ko: "차드", text_zh: " 乍得")
# Country.create(code: "TF", text_ja: "フランス領南方・南極地域", text_en: "French Southern Territories", text_ko: "남극", text_zh: " 法属南部领地")
# Country.create(code: "TG", text_ja: "トーゴ", text_en: "Togo", text_ko: "토고", text_zh: " 多哥")
Country.create(code: "TH", text_ja: "タイ", text_en: "Thailand", text_ko: "타이", text_zh: " 泰國",display_order: 28)
# Country.create(code: "TJ", text_ja: "タジキスタン", text_en: "Tajikistan", text_ko: "타지키스탄", text_zh: " 塔吉克斯坦")
# Country.create(code: "TK", text_ja: "トケラウ", text_en: "Tokelau", text_ko: "토켈라우", text_zh: " 托克勞")
# Country.create(code: "TL", text_ja: "東ティモール", text_en: "Timor-Leste", text_ko: "동티모르", text_zh: " 东帝汶")
# Country.create(code: "TM", text_ja: "トルクメニスタン", text_en: "Turkmenistan", text_ko: "투르크메니스탄", text_zh: " 土库曼斯坦")
# Country.create(code: "TN", text_ja: "チュニジア", text_en: "Tunisia", text_ko: "튀니지", text_zh: " 突尼西亞")
# Country.create(code: "TO", text_ja: "トンガ", text_en: "Tonga", text_ko: "통가", text_zh: " 汤加")
Country.create(code: "TR", text_ja: "トルコ", text_en: "Turkey", text_ko: "터키", text_zh: " 土耳其",display_order: 29)
# Country.create(code: "TT", text_ja: "トリニダード・トバゴ", text_en: "Trinidad and Tobago", text_ko: "토바고", text_zh: " 千里達及托巴哥")
# Country.create(code: "TV", text_ja: "ツバル", text_en: "Tuvalu", text_ko: "투발루", text_zh: " 图瓦卢")
Country.create(code: "TW", text_ja: "台湾（台湾省/中国）", text_en: "Taiwan, Province of China", text_ko: "중화민국", text_zh: "臺灣 臺灣",display_order: 30)
# Country.create(code: "TZ", text_ja: "タンザニア", text_en: "Tanzania, United Republic of", text_ko: "탄자니아", text_zh: " 坦桑尼亚")
# Country.create(code: "UA", text_ja: "ウクライナ", text_en: "Ukraine", text_ko: "우크라이나", text_zh: " 烏克蘭")
# Country.create(code: "UG", text_ja: "ウガンダ", text_en: "Uganda", text_ko: "우간다", text_zh: " 乌干达")
# Country.create(code: "UM", text_ja: "合衆国領有小離島", text_en: "United States Minor Outlying Islands", text_ko: "제도", text_zh: " 美國本土外小島嶼")
Country.create(code: "US", text_ja: "アメリカ合衆国", text_en: "United States", text_ko: "미국", text_zh: " 美國",display_order: 31)
# Country.create(code: "UY", text_ja: "ウルグアイ", text_en: "Uruguay", text_ko: "우루과이", text_zh: " 乌拉圭")
# Country.create(code: "UZ", text_ja: "ウズベキスタン", text_en: "Uzbekistan", text_ko: "우즈베키스탄", text_zh: " 乌兹别克斯坦")
# Country.create(code: "VA", text_ja: "バチカン市国", text_en: "Holy See (Vatican City State)", text_ko: "시국", text_zh: " 梵蒂冈")
# Country.create(code: "VC", text_ja: "セントビンセントおよびグレナディーン諸島", text_en: "Saint Vincent and the Grenadines", text_ko: "그레나딘", text_zh: " 聖文森及格瑞那丁")
# Country.create(code: "VE", text_ja: "ベネズエラ・ボリバル共和国", text_en: "Venezuela, Bolivarian Republic of", text_ko: "베네수엘라", text_zh: " 委內瑞拉")
# Country.create(code: "VG", text_ja: "イギリス領ヴァージン諸島", text_en: "Virgin Islands, British", text_ko: "버진아일랜드", text_zh: " 英屬維爾京群島")
# Country.create(code: "VI", text_ja: "アメリカ領ヴァージン諸島", text_en: "Virgin Islands, U.S.", text_ko: "버진아일랜드", text_zh: " 美屬維爾京群島")
Country.create(code: "VN", text_ja: "ベトナム", text_en: "Viet Nam", text_ko: "베트남", text_zh: " 越南",display_order: 32)
# Country.create(code: "VU", text_ja: "バヌアツ", text_en: "Vanuatu", text_ko: "바누아투", text_zh: " 瓦努阿圖")
# Country.create(code: "WF", text_ja: "ウォリス・フツナ", text_en: "Wallis and Futuna", text_ko: "퓌튀나", text_zh: " 瓦利斯和富圖納")
# Country.create(code: "WS", text_ja: "サモア", text_en: "Samoa", text_ko: "사모아", text_zh: " 萨摩亚")
# Country.create(code: "YE", text_ja: "イエメン", text_en: "Yemen", text_ko: "예멘", text_zh: " 葉門")
# Country.create(code: "YT", text_ja: "マヨット", text_en: "Mayotte", text_ko: "마요트", text_zh: " 马约特")
# Country.create(code: "ZA", text_ja: "南アフリカ", text_en: "South Africa", text_ko: "공화국", text_zh: " 南非")
# Country.create(code: "ZM", text_ja: "ザンビア", text_en: "Zambia", text_ko: "잠비아", text_zh: " 尚比亞")
# Country.create(code: "ZW", text_ja: "ジンバブエ", text_en: "Zimbabwe", text_ko: "짐바브웨", text_zh: " 辛巴威")
Country.create(code: "OT", text_ja: "その他", text_en: "Other", text_ko: "그외", text_zh: "其它",display_order: 999999)
